config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :comments

  root 'links#index'

  resources :links, only: [:new, :create, :edit, :destroy, :show] do
    resources :comments, only: [:new, :index, :create]
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :title, presence: true
  validates :url, presence: true
  belongs_to :user
  has_many :comments
  has_many :votes

  def get_votes
    self.votes.first.vote_weight
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :links
  has_many :comments
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all()
  end

  def new
    @comment = Comment.new()
  end
  
  def create
    link = Link.find(params[:link_id])
    comment = link.comments.build(comment_params)
    comment.user = current_user
    if comment.save()
     redirect_to :back
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :link_id, :user_id)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  def index
    @links = Link.all
  end

  def new
    @link = Link.new()
  end

  def create
    link = current_user.links.build(link_params)
    if link.save
      flash[:notice] = "Link successfully saved"
      redirect_to root_path
    else
      flash[:error] = "Both fields are required"
      redirect_to new_link_path 
    end
  end

  def show
    link = Link.find(params[:id])
    @comment = link.comments.build 
    @vote = Vote.find_or_create_by(user_id: current_user.id, link_id: link.id, vote_weight: 0 )
  end
  
  def edit
  end

  def update
    if @link.update(link_params)
      redirect_to root_path
    end
  end

  def destroy
    @link.destroy
    redirect_to root_path
  end

  def upvote
    vote = Vote.where("user_id = ? AND link_id= ?", current_user.id, params[:id]).take
    vote.vote_weight += 1
    vote.save()
    redirect_to :back
  end

  def downvote
    vote = Vote.where("user_id = ? AND link_id= ?", current_user.id, params[:id]).take
    vote.vote_weight -= 1
    vote.save()
    redirect_to :back
  end

  private
  def set_link
    @link = Link.find(params[:id])
  end

  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    link = Link.find(params[:link_id])
    vote = link.votes.build(vote_params) 
    vote.user = current_user 
    if vote.save()
      redirect_to :back
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:link_id, :vote_weight, :user_id)
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.body %></p>
<small>Submitted <%= time_ago_in_words comment.created_at %> by <%= comment.user.email %></small>

app/views/comments/_form.html.erb
<h1>New comment</h1>
<%= form_for @comment do |f| %>
    <%= f.label :body %>
    <div class="fom-group">
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="fom-group">
        <%= f.submit 'Comment', class: "btn btn-primary bnt-lg" %>
    </div>
<% end %>

app/views/comments/index.html.erb
<%= render @comments %>

app/views/comments/show.html.erb
<%= render @comment %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
    <% if message.is_a? String %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
            <%= content_tag :div, message %>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'partials/header' %>

<div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
</div>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f|%>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control"%>
    </div>
    <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.submit 'Submit', class:"btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/links/_link.html.erb
<div>
    <h2><%=link_to link.title, link_path(link) %></h2>
    <p>
        Submitted <%= time_ago_in_words link.created_at %> 
        by <%= link.user.name %>
    </p>
</div>
<hr>

app/views/links/edit.html.erb
<%= render 'form' %>

app/views/links/index.html.erb
<%= render @links %>

app/views/links/new.html.erb
<h1>Submit new link</h1>
<%= render 'form' %>
<%= link_to("back", links_path ) %>

app/views/links/show.html.erb
<%= render @link %>
<div class="btn-group">
    <%= link_to "Edit", edit_link_path(@link), class:"btn btn-default"%>
    <%= link_to("Destroy", @link, method: :delete, class:"btn btn-default") %>
</div>
<div>
    <%= link_to like_link_path(@link) , method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= @link.get_votes %>
    <% end %>
    <%= link_to dislike_link_path(@link) , method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        Downvote
    <% end %>
</div>
<div>
    <%= render @link.comments %>
</div>
<div>
    <h1>new comment</h1>
    <%= form_for([@link, @comment]) do |f| %>
        <%= f.label :body %>
        <div class="fom-group">
            <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="fom-group">
            <%= f.submit 'comment', class: "btn btn-primary bnt-lg" %>
        </div>
    <% end %>
</div>

app/views/partials/_header.html.erb
<header class="navbar navbar-default" role="navigation">
  <div class="navbar-inner">
    <div class="container">
      <div id="logo" class="navbar-brand"><%= link_to "Raddit", root_path %></div>
      <nav class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><a href="#">Wlecome <%= current_user.name %></a></li>
            <li><%= link_to 'Submit link', new_link_path %></li>
            <li><%= link_to("Logout", session_path , method: :delete) %></li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_path %></li>
            <li><%= link_to "Sign In", new_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-gorup">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>
  <div>
    <%= form.submit "Sign up", class: "btn btn-default btn-lg" %>
  </div>
<% end %>